#ifndef DEFAULTS_H
#define DEFAULTS_H

/* default values */
#define GENERAL_FILENAME                "undefined"
#define COMP_DOMAIN_SIZE                100
#define COMP_DOMAIN_SPACING             1e-8
#define BASIC_STEPS                     100
#define BASIC_VERBOSE                   1
#define BASIC_NTHREADS                  -1
#define BASIC_USEGPU                    FALSE
#define BASIC_UGPUINDEX                 0
#define BASIC_OUTFILE                   "out.gwy"
#define SOURCE_BOX_VERTEX0              10
#define SOURCE_BOX_VERTEXN              90
#define SOURCE_BOUNDARY_SKIP            0
#define SOURCE_BOUNDARY_SKIP_DEPTH      -1
#define SOURCE_POINT_ORIGIN_I           0
#define SOURCE_POINT_ORIGIN_J           0
#define SOURCE_POINT_ORIGIN_K           0
#define SOURCE_POINT_ORIGIN_THETA       0
#define SOURCE_POINT_ORIGIN_PHI         0
#define SOURCE_IA_THETADEG              0
#define SOURCE_IA_PHIDEG                0
#define SOURCE_IA_PSIDEG                0
#define SOURCE_PULSE_WIDTH              100
#define SOURCE_WAVELENGTH               0.633*1e-6
#define SOURCE_WAVELENGTHSPAN           0.0f
#define SOURCE_AMPLITUDE                1.0
#define SOURCE_MODE                     1
#define SOURCE_FS_THETAMAXDEG           0
#define SOURCE_FS_FDIST                 0
#define SOURCE_FS_POLARISATIONDEG       0
#define SOURCE_FS_NIP                   0
#define SOURCE_FS_MIP                   0
#define SOURCE_LAYERED_ZPOS             0
#define SOURCE_LAYERED_EPS              1
#define SOURCE_LAYERED_SIGMA            0
#define SOURCE_LAYERED_MU               1
#define SOURCE_LAYERED_SIGAST           0
#define SOURCE_LAYERED_MATERIAL         "None"
#define SOURCE_LAYERED_MATERIAL_INDEX   0
#define SOURCE_GAUSSIAN_MULT_ENABLE     0
#define SOURCE_RADIAL_MULT_ENABLE       0
#define SOURCE_FIBER_MULT_ENABLE        0
#define SOURCE_FIBER_MULT_CUTOFF        20.0f
#define SOURCE_FIBER_MULT_EPSILON_CORE  8.0f
#define SOURCE_FIBER_MULT_EPSILON_CLADDING  4.0f
#define SOURCE_XXX_MULT_CENTER          50
#define SOURCE_XXX_MULT_RADIUS          20
#define SOURCE_TSF_VALID                0
#define SOURCE_LTSF_VALID               0
#define SOURCE_TSFF_VALID               0
#define SOURCE_TSFF_SHIFT               0
#define SOURCE_LTSFF_FAST               0
#define SOURCE_LTSFF_VALID              0
#define CVBOUNDARY_TYPE                 0
#define CVBOUNDARY_DEPTH                10
#define CVBOUNDARY_M                    3
#define CVBOUNDARY_SIGMA                -1.0f
#define CVBOUNDARY_A                    0.03f
#define CVBOUNDARY_KAPPA                4.0f
#define CVBOUNDARY_MB                   FALSE
#define CVBOUNDARY_MBPOSX0              1
#define CVBOUNDARY_MBPOSXN              100
#define CVBOUNDARY_MBPOSY0              1
#define CVBOUNDARY_MBPOSYN              100
#define CVBOUNDARY_MBPOSZ0              1
#define CVBOUNDARY_MBPOSZN              100
#define MATERIAL_COUNT                  20
#define MATERIAL_MODECHECK              FALSE
#define MATERIAL_SMOOTHSTEPS            0
#define MATERIAL_GROW_I0                10
#define MATERIAL_GROW_J0                10 
#define MATERIAL_GROW_K0                10
#define MATERIAL_GROW_INBORDER          10
#define MATERIAL_GROW_JNBORDER          10
#define MATERIAL_GROW_KNBORDER          10
#define MATERIAL_GROW_SKIP              0
#define MATERIAL_GROW_ADDINDEX          1
#define MATERIAL_GROW_ATTACHINDEX       1
#define MATERIAL_GROW_SUBSAMPLING       1
#define MATERIAL_GROW_SEED              1
#define MATERIAL_GROW_NSTEPS            1
#define MATERIAL_GROW_MOBILITY          0.5f
#define MATERIAL_GROW_PROBABILITY       0.5f
#define MATERIAL_ROUGHNESS_MATINDEX     1
#define MATERIAL_ROUGHNESS_VOIDINDEX   0
#define MATERIAL_ROUGHNESS_ITERATIONS   5
#define MATERIAL_ROUGHNESS_SEED         -1
#define MATERIAL_ROUGHNESS_RADIUSPEAK   10
#define MATERIAL_ROUGHNESS_RADIUSSPAN   2
#define MATERIAL_ROUGHNESS_PROBABILITY  0.01f
#define MATERIAL_SPECTRAL_MATINDEX      1
#define MATERIAL_SPECTRAL_SIGMA         3.0f
#define MATERIAL_SPECTRAL_T             10.0f
#define MATERIAL_SPECTRAL_SEED          -1
#define MATERIAL_EXPR_I0                10
#define MATERIAL_EXPR_J0                10 
#define MATERIAL_EXPR_K0                10
#define MATERIAL_EXPR_INBORDER          10
#define MATERIAL_EXPR_JNBORDER          10
#define MATERIAL_EXPR_KNBORDER          10
#define MATERIAL_EXPR_MATINDEX          1
#define MATERIAL_EXPR_VOIDINDEX         0
#define MATERIAL_EXPR_MAXDIST           10
#define MATERIAL_EXPR_DISTMODE          1
#define MATERIAL_EXPR_EXPR              "sin(x)"
#define MATERIAL_EXPR_EXPR_CHARS        512
#define POINT_OUTPUT_ORIGIN_I           0
#define POINT_OUTPUT_ORIGIN_J           0
#define POINT_OUTPUT_ORIGIN_K           0
#define IMAGE_OUTPUT_ORIGIN_I           0
#define PLANE_OUTPUT_ORIGIN_I           0
#define VOLUME_OUTPUT_ORIGIN_I          0
#define OUTPUT_STEP                     10
#define OUTPUT_COMPONENT                0
#define OUTPUT_START                    0
#define OUTPUT_STOP                     1000
#define OUTPUT_FORMAT                   0
#define OUTPUT_PLANE                    0
#define OUTPUT_BOX_I0                   0
#define OUTPUT_BOX_J0                   0
#define OUTPUT_BOX_K0                   0
#define OUTPUT_BOX_IN                   0
#define OUTPUT_BOX_JN                   0
#define OUTPUT_BOX_KN                   0
#define OUTPUT_POINT_POS                50
#define OUTPUT_IMAGE_POSI               50
#define OUTPUT_IMAGE_POSJ               -1
#define OUTPUT_IMAGE_POSK               -1
#define OUTPUT_PLANE_POSI               50
#define OUTPUT_PLANE_POSJ               -1
#define OUTPUT_PLANE_POSK               -1
#define OUTPUT_VOLUME_POSI              50
#define OUTPUT_VOLUME_POSJ              -1
#define OUTPUT_VOLUME_POSK              -1
#define OUTPUT_SUM_VERTEX0              10
#define OUTPUT_SUM_VERTEXN              50
#define OUTPUT_SUM_EPS                  1
#define OUTPUT_SUM_MU                   1
#define OUTPUT_SUM_SIGMA                0
#define OUTPUT_SUM_SIGAST               0
#define OUTPUT_FORCE_VERTEX0            10
#define OUTPUT_FORCE_VERTEXN            50
#define NFFF_BOX_VERTEX0                10
#define NFFF_BOX_VERTEXN                90
#define NFFF_BOX_BOUNDARY_SKIP          0
#define NFFF_SKIPI0                     0
#define NFFF_SKIPIN                     0
#define NFFF_SKIPJ0                     0
#define NFFF_SKIPJN                     0
#define NFFF_SKIPK0                     0
#define NFFF_SKIPKN                     0
#define NFFFP_POS_I                     100
#define NFFFP_POS_J                     100
#define NFFFP_POS_K                     100
#define NFFFP_INDIVIDUAL                0
#define NFFFA_THETARES                  10
#define NFFFA_PHIRES                    10
#define NFFFA_RADIUS                    1000
#define NFFFA_SAVEFILE                  0
#define NFFFA_THETAFROMDEG              0
#define NFFFA_THETATODEG                10
#define NFFFA_PHIFROMDEG                0
#define NFFFA_PHITODEG                  10
#define PNFFF_BOX_VERTEX0               10
#define PNFFF_BOX_VERTEXN               90
#define PNFFF_BOX_BOUNDARY_SKIP         0
#define PNFFF_SKIPK0                    0
#define PNFFF_SKIPKN                    0
#define PNFFFP_POS_I                    100
#define PNFFFP_POS_J                    100
#define PNFFFP_POS_K                    100
#define PNFFFP_INDIVIDUAL               0
#define PNFFF_INTEGRATION_XMIN          0
#define PNFFF_INTEGRATION_XMAX          1
#define PNFFF_INTEGRATION_YMIN          0
#define PNFFF_INTEGRATION_YMAX          1
#define PNFFFA_THETARES                 10
#define PNFFFA_PHIRES                   10
#define PNFFFA_RADIUS                   1000
#define PNFFFA_SAVEFILE                 0
#define PNFFFA_THETAFROMDEG             0
#define PNFFFA_THETATODEG               10
#define PNFFFA_PHIFROMDEG               0
#define PNFFFA_PHITODEG                 10
#define MAT_SPHERE_CENTER_I             50.0f
#define MAT_SPHERE_CENTER_J             50.0f
#define MAT_SPHERE_CENTER_K             50.0f
#define MAT_SPHERE_RADIUS               10.0f
#define MAT_VOXEL_I0                    40.0f
#define MAT_VOXEL_J0                    40.0f
#define MAT_VOXEL_K0                    40.0f
#define MAT_VOXEL_IN                    60.0f
#define MAT_VOXEL_JN                    60.0f
#define MAT_VOXEL_KN                    60.0f
#define MAT_CYLINDER_I0                 40.0f
#define MAT_CYLINDER_J0                 40.0f
#define MAT_CYLINDER_K0                 40.0f
#define MAT_CYLINDER_IN                 60.0f
#define MAT_CYLINDER_JN                 60.0f
#define MAT_CYLINDER_KN                 60.0f
#define MAT_CYLINDER_RADIUS             10.0f
#define MAT_CONE_I0                     40.0f
#define MAT_CONE_J0                     40.0f
#define MAT_CONE_K0                     40.0f
#define MAT_CONE_IN                     60.0f
#define MAT_CONE_JN                     60.0f
#define MAT_CONE_KN                     60.0f
#define MAT_CONE_RADIUS                 10.0f
#define MAT_RCONE_I0                    40.0f
#define MAT_RCONE_J0                    40.0f
#define MAT_RCONE_K0                    40.0f
#define MAT_RCONE_IN                    60.0f
#define MAT_RCONE_JN                    60.0f
#define MAT_RCONE_KN                    60.0f
#define MAT_RCONE_RADIUS1               5.0f
#define MAT_RCONE_RADIUS2               10.0f
#define MAT_TTHN_I1                     40.0f
#define MAT_TTHN_J1                     50.0f
#define MAT_TTHN_K1                     50.0f
#define MAT_TTHN_I2                     60.0f
#define MAT_TTHN_J2                     50.0f
#define MAT_TTHN_K2                     50.0f
#define MAT_TTHN_I3                     50.0f
#define MAT_TTHN_J3                     40.0f
#define MAT_TTHN_K3                     50.0f
#define MAT_TTHN_I4                     50.0f
#define MAT_TTHN_J4                     50.0f
#define MAT_TTHN_K4                     60.0f
#define MAT_PROP_TYPE                   0
#define MAT_PROP_EPS                    1.0f
#define MAT_PROP_MU                     1.0f
#define MAT_PROP_SIGMA                  0.0f
#define MAT_PROP_SIGAST                 0.0f
#define MAT_PROP_CEPS                   1.0f
#define MAT_PROP_OMEGA                  0.0f
#define MAT_PROP_NU                     0.0f
#define MAT_PROP_A                      1.0f
#define MAT_PROP_PHI                    1.0f
#define MAT_PROP_OMEGA                  0.0f
#define MAT_PROP_GAMMA                  0.0f
#define MAT_PROP_MATERIAL_NONE          "None"
#define MAT_PROP_MATERIAL_NONE_INDEX    0
#define MAT_PROP_POS                    -1
#define MAT_PROP_METAL_MODEL            1

#endif /* DEFAULTS_H */
